const COUNTRY_ALIASES: Record<string, string> = {
  'UNITED KINGDOM': 'GB',
  'UK': 'GB',
  'GREAT BRITAIN': 'GB',
  'ENGLAND': 'GB',
  'SCOTLAND': 'GB',
  'WALES': 'GB',
  'NORTHERN IRELAND': 'GB',
  'UNITED STATES': 'US',
  'USA': 'US',
  'U.S.A.': 'US',
  'UNITED STATES OF AMERICA': 'US',
  'UNITED ARAB EMIRATES': 'AE',
  'UAE': 'AE',
  'U.A.E.': 'AE',
  'SAUDI ARABIA': 'SA',
  'KSA': 'SA',
  'TURKEY': 'TR',
  'TÜRKİYE': 'TR',
  'TURKIYE': 'TR',
  'SOUTH KOREA': 'KR',
  'KOREA, REPUBLIC OF': 'KR',
  'NETHERLANDS': 'NL',
  'HOLLAND': 'NL',
  'THE NETHERLANDS': 'NL',
  'GERMANY': 'DE',
  'FRANCE': 'FR',
  'SPAIN': 'ES',
  'ITALY': 'IT',
  'CANADA': 'CA',
  'INDIA': 'IN',
  'AUSTRALIA': 'AU',
  'JAPAN': 'JP',
  'CHINA': 'CN',
  'BRAZIL': 'BR',
  'MEXICO': 'MX',
  'RUSSIA': 'RU',
  'PORTUGAL': 'PT',
  'GREECE': 'GR',
  'SWITZERLAND': 'CH',
  'BELGIUM': 'BE',
  'SWEDEN': 'SE',
  'NORWAY': 'NO',
  'DENMARK': 'DK',
  'FINLAND': 'FI',
  'IRELAND': 'IE',
  'POLAND': 'PL',
  'CZECH REPUBLIC': 'CZ',
  'AUSTRIA': 'AT',
  'THAILAND': 'TH',
  'SINGAPORE': 'SG',
  'MALAYSIA': 'MY',
  'INDONESIA': 'ID',
  'PHILIPPINES': 'PH',
  'VIETNAM': 'VN',
  'NEW ZEALAND': 'NZ',
  'SOUTH AFRICA': 'ZA',
  'EGYPT': 'EG',
  'MOROCCO': 'MA',
  'ARGENTINA': 'AR',
  'COLOMBIA': 'CO',
  'PERU': 'PE',
  'CHILE': 'CL',
  'CROATIA': 'HR',
  'HUNGARY': 'HU',
  'CZECHIA': 'CZ',
  'ROMANIA': 'RO',
  'BULGARIA': 'BG',
  'UKRAINE': 'UA',
  'TURKS AND CAICOS ISLANDS': 'TC',
  'BRITISH VIRGIN ISLANDS': 'VG',
  'CAYMAN ISLANDS': 'KY',
  'BERMUDA': 'BM',
  'GIBRALTAR': 'GI',
  'ISLE OF MAN': 'IM',
  'JERSEY': 'JE',
  'GUERNSEY': 'GG',
};

const ISO3_TO_ISO2: Record<string, string> = {
  'UAE': 'AE',
  'GBR': 'GB',
  'USA': 'US',
  'CAN': 'CA',
  'AUS': 'AU',
  'IND': 'IN',
  'DEU': 'DE',
  'FRA': 'FR',
  'ESP': 'ES',
  'ITA': 'IT',
  'NLD': 'NL',
  'PRT': 'PT',
  'BRA': 'BR',
  'CHN': 'CN',
  'JPN': 'JP',
  'KOR': 'KR',
  'RUS': 'RU',
  'SAU': 'SA',
  'TUR': 'TR',
  'MEX': 'MEX',
  'ZAF': 'ZA',
  'ARG': 'AR',
  'CHE': 'CH',
  'BEL': 'BE',
  'SWE': 'SE',
  'NOR': 'NO',
  'DNK': 'DK',
  'FIN': 'FI',
  'IRL': 'IE',
  'POL': 'PL',
  'CZE': 'CZ',
  'AUT': 'AT',
  'THA': 'TH',
  'SGP': 'SG',
  'MYS': 'MY',
  'IDN': 'ID',
  'PHL': 'PH',
  'VNM': 'VN',
  'NZL': 'NZ',
  'EGY': 'EG',
  'MAR': 'MA',
  'COL': 'CO',
  'PER': 'PE',
  'CHL': 'CL',
  'HRV': 'HR',
  'HUN': 'HU',
  'ROU': 'RO',
  'BGR': 'BG',
  'UKR': 'UA',
  'GRC': 'GR',
  'PAN': 'PA',
  'CRI': 'CR',
  'DOM': 'DO',
  'JAM': 'JM',
  'BHS': 'BS',
  'BRB': 'BB',
  'TTO': 'TT',
  'KEN': 'KE',
  'NGA': 'NG',
  'GHA': 'GH',
  'PAK': 'PK',
  'BGD': 'BD',
  'LKA': 'LK',
  'NPL': 'NP',
  'MMR': 'MM',
  'KHM': 'KH',
  'LAO': 'LA',
  'VUT': 'VU',
  'FJI': 'FJ',
  'PNG': 'PG',
};

export function normalizeCountryCode(input?: string): string {
  if (!input) return '';

  const raw = String(input).trim();
  const upper = raw.toUpperCase();

  if (COUNTRY_ALIASES[upper]) {
    return COUNTRY_ALIASES[upper];
  }

  if (upper.length === 2 && /^[A-Z]{2}$/.test(upper)) {
    return upper;
  }

  if (upper.length === 3 && /^[A-Z]{3}$/.test(upper)) {
    if (ISO3_TO_ISO2[upper]) {
      return ISO3_TO_ISO2[upper];
    }
  }

  return upper.substring(0, 2);
}
